name: Build and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - adservice
          - cartservice
          - checkoutservice
          - currencyservice
          - emailservice
          - frontend
          - loadgenerator
          - paymentservice
          - productcatalogservice
          - recommendationservice
          - shippingservice
          - shoppingservice
          - shoppingassistantservice

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Log in to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 715841344530.dkr.ecr.eu-central-1.amazonaws.com

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./src/${{ matrix.service }}/src/
          file: ./src/${{ matrix.service }}/src/Dockerfile
          push: true
          tags: 715841344530.dkr.ecr.eu-central-1.amazonaws.com/workspace/sock-shop/${{ matrix.service }}:latest
